on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
    steps:
      - name: Install SWI-Prolog on macOS
        if: runner.os == 'macOS'
        run: brew install swi-prolog
      - name: Install SWI-Prolog on Windows
        if: runner.os == 'Windows'
        run: choco install SWI-Prolog
      - name: Install SWI-Prolog on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install swi-prolog
      - uses: actions/checkout@v2
