on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{matrix.config.os}}
    name: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
    steps:
      - name: Install SWI-Prolog
        if: runner.os == 'Linux'
        run: |
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install swi-prolog
      - uses: actions/checkout@v2
