on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{matrix.config.os}}
    name: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v2
