on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test

jobs:
  pack-cover:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Windows, Ubuntu]
    steps:
      - uses: actions/checkout@v2
      - uses: royratcliffe/swi-prolog-pack-cover@failed-in-file
        env:
          GHAPI_PAT: ${{ secrets.GHAPI_PAT }}
          COVFAIL_GISTID: ${{ secrets.COVFAIL_GISTID }}
